cluster_admin_user: slawek
cluster_timezone: Europe/Warsaw

base_host_packages:
  - ca-certificates
  - curl
  - dos2unix
  - git
  - gnupg
  - jq
  - unzip

base_host_directories:
  - path: /srv
    owner: root
    group: root
    mode: '0755'
  - path: /srv/backups
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/backups/postgres
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/cloudwatch
    owner: root
    group: root
    mode: '0755'
  - path: /srv/cloudwatch/state
    owner: root
    group: root
    mode: '0755'
  - path: /srv/gateway
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/gateway/html
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/logs
    owner: root
    group: root
    mode: '0755'
  - path: /srv/logs/database
    owner: '999'
    group: '999'
    mode: '0755'
  - path: /srv/logs/gateway
    owner: root
    group: root
    mode: '0755'
  - path: /srv/logs/sg-application
    owner: '77777'
    group: '77777'
    mode: '0755'
  - path: /srv/logs/sg-banks
    owner: '77777'
    group: '77777'
    mode: '0755'
  - path: /srv/postgres
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/postgres-hot-standby
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/registry
    owner: slawek
    group: slawek
    mode: '0755'
  - path: /srv/registry/data
    owner: slawek
    group: slawek
    mode: '0755'
