version: '3.8'

x-docker-json-logging: &docker_json_logging
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'

services:
  postgres:
    image: postgres:18.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
    secrets:
      - postgres_password
    volumes:
      - type: bind
        source: /srv/cluster/data/postgres
        target: /var/lib/postgresql
      - type: bind
        source: /srv/cluster/backups/postgres
        target: /backups
    networks:
      - application_network
      - cluster_network
    logging: *docker_json_logging
    deploy:
      placement:
        constraints:
          - node.labels.workload.postgres == true
      restart_policy:
        condition: any

  postgres-backup:
    image: postgres:18.4
    user: '1000:1000'
    environment:
      DATABASE_HOST: database_postgres
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
    secrets:
      - postgres_password
    configs:
      - source: postgres_backup_script
        target: /usr/local/bin/backup-data
        uid: '1000'
        gid: '1000'
        mode: 0550
    volumes:
      - type: bind
        source: /srv/cluster/backups/postgres
        target: /backups
    networks:
      - application_network
      - cluster_network
    logging: *docker_json_logging
    entrypoint:
      - /bin/bash
      - /usr/local/bin/backup-data
    deploy:
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 * * * *
        - swarm.cronjob.skip-running=false
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.workload.postgres == true

configs:
  postgres_backup_script:
    file: ../configs/database/backup-data.sh
    name: postgres_backup_script_${CONFIG_VERSION:-0}
  postgres_restore_script:
    file: ../configs/database/restore-data.sh
    name: postgres_restore_script_${CONFIG_VERSION:-0}

secrets:
  postgres_password:
    external: true

networks:
  application_network:
    external: true
  cluster_network:
    external: true
