version: '3.8'

services:
  fluent-bit:
    image: fluent/fluent-bit:5.1.1
    environment:
      AWS_REGION: eu-central-1
      AWS_PROFILE: AmazonCloudWatchAgent
      HOST_NODE: '{{.Node.Hostname}}'
    secrets:
      - source: cloudwatch_credentials
        target: /root/.aws/credentials
    configs:
      - source: fluent_bit_config
        target: /fluent-bit/etc/fluent-bit.conf
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /srv/cluster/data/cloudwatch:/var/fluent-bit/state
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.workload.observability == true
      restart_policy:
        condition: any

secrets:
  cloudwatch_credentials:
    external: true

configs:
  fluent_bit_config:
    file: ../configs/infrastructure/fluent-bit.conf
    name: fluent_bit_config_${CONFIG_VERSION:-0}
