[SERVICE]
    Flush                     5
    Grace                     30
    Log_Level                 info
    Parsers_File              /fluent-bit/etc/parsers.conf
    storage.path              /var/fluent-bit/state/storage
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 50M

[INPUT]
    Name               tail
    Tag                docker.*
    Path               /var/lib/docker/containers/*/*-json.log
    Parser             docker
    Path_Key           container_log_path
    DB                 /var/fluent-bit/state/docker-containers.db
    Mem_Buf_Limit      25MB
    Skip_Long_Lines    On
    Refresh_Interval   5
    Rotate_Wait        30
    Read_from_Head     Off
    storage.type       filesystem

[OUTPUT]
    Name              cloudwatch_logs
    Match             docker.*
    region            ${AWS_REGION}
    log_group_name    docker-containers
    log_stream_name   ${HOST_NODE}
    auto_create_group true
    retry_limit       false
