all:
  children:
    bootstrap_hosts:
      hosts:
        PC2:
          ansible_host: 192.168.20.2
        rpi3:
          ansible_host: 192.168.20.3
        rpi4:
          ansible_host: 192.168.20.4
        rpi5:
          ansible_host: 192.168.20.5
    swarm_managers:
      hosts:
        PC2:
    swarm_workers:
      hosts:
        rpi5:
        rpi4:
        rpi3:
    postgres_nodes:
      hosts:
        rpi3:
    registry_nodes:
      hosts:
        rpi5:
    gateway_nodes:
      hosts:
        PC2:
    application_nodes:
      hosts:
        PC2:
    observability_nodes:
      hosts:
        PC2:
        rpi5:
        rpi4:
        rpi3:
    letsencrypt_hosts:
      hosts:
        PC2:
  vars:
    firewall_cluster_network: 192.168.20.0/24
    firewall_ssh_networks:
      - 192.168.20.0/24
      - 192.168.52.0/24
    base_host_ssh_config_hosts:
      - 192.168.20.2
      - 192.168.20.3
      - 192.168.20.4
      - 192.168.20.5
