all:
  children:
    bootstrap_hosts:
      hosts:
        PC2:
          ansible_host: PC2
        rpi5:
          ansible_host: rpi5
        rpi4:
          ansible_host: rpi4
        rpi3:
          ansible_host: rpi3
    swarm_managers:
      hosts:
        PC2:
    swarm_workers:
      hosts:
        rpi5:
        rpi4:
        rpi3:
    postgres_nodes:
      hosts:
        rpi3:
    registry_nodes:
      hosts:
        rpi5:
    letsencrypt_hosts:
      hosts:
        PC2:
  vars:
    firewall_cluster_network: 192.168.20.0/24
    base_host_ssh_config_hosts:
      - PC2
      - rpi5
      - rpi4
      - rpi3
