#!/bin/bash

export CLUSTER_HOME=/home/slawek

export SRV_DIR=/srv
export POSTGRES_DATA_DIR=$SRV_DIR/postgres
export POSTGRES_HOTSTANDBY_DATA_DIR=$SRV_DIR/postgres-hot-standby
export MYSQL_DATA_DIR=$SRV_DIR/mysql

export CLUSTER_DIR=$CLUSTER_HOME/Cluster
export SECRETS_DIR=$CLUSTER_DIR/secrets
export PERMANENT_DATA_DIR=$SRV_DIR
export CORE_GATEWAY_HTML_DIR=$SRV_DIR/gateway/html
export CORE_GATEWAY_LOGS_DIR=$SRV_DIR/logs/gateway
export CORE_REGISTRY_DATA_DIR=$SRV_DIR/registry/data
export DATABASE_BACKUPS_DIR=$SRV_DIR/backups/postgres
export DATABASE_LOGS_DIR=$SRV_DIR/logs/database
export SG_APPLICATION_LOGS_DIR=$SRV_DIR/logs/sg-application
export SG_BANKS_LOGS_DIR=$SRV_DIR/logs/sg-banks
export CLOUDWATCH_STATE_DIR=$SRV_DIR/cloudwatch/state

export CORE_DIR=$CLUSTER_DIR/core
export CORE_MANAGEMENT_DIR=$CORE_DIR/management
export CORE_SETUP_DIR=$CORE_DIR/setup
export CORE_STACK_DIR=$CORE_DIR/stack
export CORE_CONFIG_DIR=$CORE_STACK_DIR/config
export REGISTRY_DIR=$CORE_STACK_DIR/registry

export DB_DIR=$CLUSTER_DIR/db
export DB_MANAGEMENT_DIR=$DB_DIR/management
export DB_SETUP_DIR=$DB_DIR/setup
export DB_STACK_DIR=$DB_DIR/stack

export DB_MYSQL_DIR=$CLUSTER_DIR/db_mysql
export DB_MYSQL_MANAGEMENT_DIR=$DB_MYSQL_DIR/management

export SG_APPLICATION_DIR=$CLUSTER_DIR/sg-application
export SG_APPLICATION_MANAGEMENT_DIR=$SG_APPLICATION_DIR/management
export APPLICATION_STACK_DIR=$SG_APPLICATION_DIR/stack
export APPLICATION_CONFIG_DIR=$APPLICATION_STACK_DIR/config

export INFRASTRUCTURE_DIR=$CLUSTER_DIR/infrastructure
export INFRASTRUCTURE_MANAGEMENT_DIR=$INFRASTRUCTURE_DIR/management
export INFRASTRUCTURE_SETUP_DIR=$INFRASTRUCTURE_DIR/setup
export INFRASTRUCTURE_STACK_DIR=$INFRASTRUCTURE_DIR/stack
export INFRASTRUCTURE_CONFIG_DIR=$INFRASTRUCTURE_STACK_DIR/config
