version: '3.8'

services:
  cloudwatch-agent:
    image: amazon/cloudwatch-agent:latest
    environment:
      AWS_REGION: eu-central-1
    secrets:
      - source: cloudwatch_credentials
        target: /root/.aws/credentials
    configs:
      - source: cloudwatch-config.json
        target: /etc/cwagentconfig/config.json
      - source: cloudwatch-common-config.toml
        target: /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml
    volumes:
      - $SG_APPLICATION_LOGS_DIR:/logs/sg-application:ro
      - $SG_BANKS_LOGS_DIR:/logs/sg-banks:ro
      - $CORE_GATEWAY_LOGS_DIR:/logs/core-gateway:ro
      - $DATABASE_LOGS_DIR:/logs/database:ro
      - $CLOUDWATCH_STATE_DIR:/opt/aws/amazon-cloudwatch-agent/var
#      - $INFRASTRUCTURE_CONFIG_DIR/cloudwatch-config.json:/etc/cwagentconfig/config.json
#      - $INFRASTRUCTURE_CONFIG_DIR/cloudwatch-common-config.toml:/opt/aws/amazon-cloudwatch-agent/etc/common-config.toml
    deploy:
      mode: global
      restart_policy:
        condition: any

secrets:
  cloudwatch_credentials:
    external: true

configs:
  cloudwatch-config.json:
    file: config/cloudwatch-config.json
  cloudwatch-common-config.toml:
    file: config/cloudwatch-common-config.toml
