version: '3.8'

services:

  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Warsaw"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role==manager
          - node.hostname==PC2

  gateway:
    image: nginx:1.25.4-bookworm
    container_name: nginx
    ports:
      - 80:80
      - 5005:5005
      - 443:443
    secrets:
      - sgapplication.crt
      - sgapplication.key
      - sgapplication2.crt
      - sgapplication2.key
    volumes:
      - $CORE_CONFIG_DIR/nginx.conf:/etc/nginx/nginx.conf:ro
      - $SECRETS_DIR/htpasswd:/auth/htpasswd:ro
      - $CORE_GATEWAY_HTML_DIR:/usr/share/nginx:ro
      - $CORE_GATEWAY_LOGS_DIR:/var/log/nginx
    networks:
      - cluster_network
      - sg_app_network
    depends_on:
      - zot
    deploy:
      placement:
        constraints:
          - node.hostname==PC2

  zot:
    image: ghcr.io/project-zot/zot:v2.1.20
    configs:
      - source: zot-config.json
        target: /etc/zot/config.json
    volumes:
      - $CORE_REGISTRY_DATA_DIR:/var/lib/registry
    networks:
      - cluster_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.registry == true
      restart_policy:
        condition: on-failure

  t310-reader:
    image: t310-reader:1.0.1
    secrets:
      - smart_home_db_host
      - smart_home_db_password
      - tapo_user
      - tapo_password
      - tapo_device_ip
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=* * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname==PC2

secrets:
  smart_home_db_host:
    external: true
  smart_home_db_password:
    external: true
  tapo_user:
    external: true
  tapo_password:
    external: true
  tapo_device_ip:
    external: true
  sgapplication.crt:
    file: $SECRETS_DIR/certs/sgapplication.crt
  sgapplication.key:
    file: $SECRETS_DIR/certs/sgapplication.key
  sgapplication2.crt:
    file: $SECRETS_DIR/certs/sgapplication2.crt
  sgapplication2.key:
    file: $SECRETS_DIR/certs/sgapplication2.key

configs:
  zot-config.json:
    file: config/zot-config.json

networks:
  cluster_network:
    name: cluster_network
  sg_app_network:
    external: true
