#!/usr/bin/env bash
set -Eeuo pipefail

stack_name="${1:-}"
case "$stack_name" in
  core|database|application|infrastructure) ;;
  *)
    echo "Usage: $(basename "$0") {core|database|application|infrastructure}" >&2
    exit 2
    ;;
esac

cluster_root="${CLUSTER_ROOT:-/srv/cluster}"
current_link="$cluster_root/current"
release_directory="$(readlink -f -- "$current_link")"

if [[ -z "$release_directory" || ! -d "$release_directory" ]]; then
  echo "No active release at $current_link." >&2
  exit 1
fi

release_id="$(basename -- "$release_directory")"
if [[ ! "$release_id" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]; then
  echo "Unsafe release identifier: $release_id" >&2
  exit 1
fi

compose_file="$release_directory/stacks/$stack_name.yml"
if [[ ! -f "$compose_file" ]]; then
  echo "Stack file does not exist: $compose_file" >&2
  exit 1
fi

export CONFIG_VERSION="${release_id:0:12}"

image_tags_file="$cluster_root/image-tags.env"
if [[ -r "$image_tags_file" ]]; then
  while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" == \#* ]] && continue
    case "$key" in
      FRONTEND_IMAGE_TAG|BACKEND_IMAGE_TAG|BANKS_IMAGE_TAG)
        if [[ "$value" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$ ]]; then
          export "$key=$value"
        else
          echo "Invalid $key in $image_tags_file." >&2
          exit 1
        fi
        ;;
      *)
        echo "Unknown setting in $image_tags_file: $key" >&2
        exit 1
        ;;
    esac
  done < "$image_tags_file"
fi

observability_environment="$cluster_root/observability.env"
if [[ -r "$observability_environment" ]]; then
  set -a
  source "$observability_environment"
  set +a
fi

if [[ ! "${LOGGING_SYSLOG_ADDRESS:-}" =~ ^tcp://[^[:space:]/:]+:[0-9]{1,5}$ ]]; then
  echo "Missing or invalid LOGGING_SYSLOG_ADDRESS in $observability_environment." >&2
  echo "Run the Docker Swarm Ansible provisioning before deploying stacks." >&2
  exit 1
fi

if [[ "$stack_name" == core ]]; then
  certificate_environment="$cluster_root/certificates/letsencrypt/current-secrets.env"
  if [[ ! -r "$certificate_environment" ]]; then
    echo "Certificate secret metadata is missing: $certificate_environment" >&2
    echo "Run $cluster_root/bin/renew-certificates before deploying the core stack." >&2
    exit 1
  fi

  set -a
  # The file is generated by the root-owned renewal script and contains only
  # the two current Docker secret names.
  source "$certificate_environment"
  set +a

  for secret_name in \
    "${GATEWAY_TLS_CERTIFICATE_SECRET:-}" \
    "${GATEWAY_TLS_PRIVATE_KEY_SECRET:-}"; do
    if [[ ! "$secret_name" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]; then
      echo "Invalid certificate secret name in $certificate_environment." >&2
      exit 1
    fi
  done
fi

docker stack config --compose-file "$compose_file" >/dev/null
docker stack deploy \
  --compose-file "$compose_file" \
  --prune \
  --resolve-image changed \
  --with-registry-auth \
  "$stack_name"

# Docker configs are immutable. A release-specific name updates services
# safely; versions no longer referenced by a service can then be removed.
while IFS= read -r config_name; do
  case "$config_name" in
    gateway_nginx_*|registry_config_*|\
    postgres_backup_script_*|postgres_restore_script_*|\
    backend_application_*|banks_application_*|backend_logback_*|banks_logback_*|\
    fluent_bit_config_*|cloudwatch_config_*|cloudwatch_common_config_*|\
    alloy_config_*|loki_config_*|prometheus_config_*|grafana_datasources_*)
      config_stack="$(docker config inspect "$config_name" \
        --format '{{ index .Spec.Labels "com.docker.stack.namespace" }}' 2>/dev/null || true)"
      if [[ "$config_stack" =~ ^(core|database|application|infrastructure)$ && \
            "$config_name" != *_"$CONFIG_VERSION" ]]; then
        if docker config rm "$config_name" >/dev/null 2>&1; then
          echo "Removed unused Docker config: $config_name"
        fi
      fi
      ;;
  esac
done < <(docker config ls --format '{{.Name}}')
