version: '3.8'

services:

  database:
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: app
        awslogs-stream: db
        awslogs-create-group: 'true'
    image: postgres:18.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
    secrets:
      - postgres_password
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql
      - $DATABASE_BACKUP_DIR:/backup
    networks:
      - sg_app_network
      - cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname==rpi5

  database_backup:
    image: postgres:18.4
    restart: always
    user: "1000:1000"
    environment:
      PGPASSWORD: /run/secrets/postgres_password
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
    secrets:
      - postgres_password
    volumes:
      - $DATABASE_BACKUP_DIR:/backup
      - $DATABASE_ACCOUNTANT_BACKUPS_DIR:/accountant_backups
      - $DATABASE_BANKS_BACKUPS_DIR:/banks_backups
      - $DATABASE_SMART_HOME_BACKUPS_DIR:/smart_home_backups
      - $DB_MANAGEMENT_DIR/backup_data.sh:/backup_data.sh
    networks:
      - sg_app_network
      - cluster_network
    entrypoint: ["/bin/bash", "/backup_data.sh"]
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname==rpi5

secrets:
  postgres_password:
    external: true

networks:
  sg_app_network:
    name: sg_app_network
  cluster_network:
    external: true