version: '3.8'

services:

  database:
    image: postgres:18.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_directory=/var/log/postgresql
      - -c
      - log_filename=postgres-%Y-%m-%d_%H%M%S.log
      - -c
      - log_rotation_age=1d
      - -c
      - log_rotation_size=100MB
      - -c
      - log_truncate_on_rotation=on
    secrets:
      - postgres_password
    volumes:
      - $POSTGRES_DATA_DIR:/var/lib/postgresql
      - $DATABASE_BACKUPS_DIR:/backups
      - $DATABASE_LOGS_DIR:/var/log/postgresql
    networks:
      - sg_app_network
      - cluster_network
    deploy:
      placement:
        constraints:
          - node.hostname==rpi5

  database_backup:
    image: postgres:18.4
    restart: always
    user: "1000:1000"
    environment:
      PGPASSWORD: /run/secrets/postgres_password
      TZ: Europe/Warsaw
      PGTZ: Europe/Warsaw
    secrets:
      - postgres_password
    volumes:
      - $DATABASE_BACKUPS_DIR:/backups
      - $DB_MANAGEMENT_DIR/backup_data.sh:/backup_data.sh
    networks:
      - sg_app_network
      - cluster_network
    entrypoint: ["/bin/bash", "/backup_data.sh"]
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname==rpi5

secrets:
  postgres_password:
    external: true

networks:
  sg_app_network:
    external: true
  cluster_network:
    external: true
