---
- name: Enable automatic system time synchronization
  ansible.builtin.command:
    cmd: timedatectl set-ntp true
  changed_when: false

- name: Ensure the system time synchronization service is running
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    enabled: true
    state: started

- name: Force the system time synchronization service to resynchronize
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    state: restarted

- name: Wait for the system clock to synchronize
  ansible.builtin.command:
    cmd: timedatectl show --property=NTPSynchronized --value
  register: base_host_ntp_synchronized
  changed_when: false
  until: base_host_ntp_synchronized.stdout | trim == 'yes'
  retries: "{{ base_host_time_sync_retries }}"
  delay: "{{ base_host_time_sync_delay }}"
