name: deploy latest banks

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Deploy the latest banks
        id: deploy_latest_banks
        uses: appleboy/ssh-action@master
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          REGISTRY: ${{ secrets.SG_REGISTRY_URL }}
          REPOSITORY: banks
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 10000
          script: |
            docker service update --force --image ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest application_banks
